### ISSUE TITLE
Navigation Bar Active page is not visible.

### ISSUE THREAD

**Issue by karthikchiru12** [karthikchiru12/Algovis#7]
Previously when each page is loaded, the navigation bar highlighted the current page. But now it is missing probably because of the bootstrap class (class= "nav-item active") missing.

**Comment by sripravan** [comment]
Commits 76c8d17e0cdd2627909b73c0955d1df636799be4 and 55c748a0317cdef278b552eedaefa58c999c0f1f fix the issue.
